application.type=DATASET_POPULATION
debt-ranking.count=0
debt-ranking.file=debt_ranking_
debt-ranking.touched=1
effort-ranking.count=0
effort-ranking.file=effort_ranking_
effort-ranking.touched=1
project.name=SYNCOPE
smells-ranking.count=0
smells-ranking.file=smells_ranking_
smells-ranking.touched=1
sonar.project.key=gianpaolo-pestilli_syncope2
