# Secrets
token=ec515101428bf24b956676c35e030eecfb3ed473
path=C:/Users/tpest/Desktop/Syncope/syncope
project.owner=gianpaolo-pestilli
project.repo=syncope
sonar.path=C:\\Users\\tpest\\Downloads\\sonar-scanner-cli-8.0.1.6346-windows-x64\\sonar-scanner-8.0.1.6346-windows-x64\\bin\\sonar-scanner.bat